/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InstructionsRouteImport } from './routes/instructions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NomineesRouteImport } from './routes/nominees'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as NomineeAccessRouteImport } from './routes/nominee/access'
import { Route as NomineeChecklistRouteImport } from './routes/nominee/checklist'
import { Route as NomineeDashboardRouteImport } from './routes/nominee/dashboard'
import { Route as NomineeFinancialRouteImport } from './routes/nominee/financial'
import { Route as NomineeInstructionsRouteImport } from './routes/nominee/instructions'
import { Route as NomineeLoginRouteImport } from './routes/nominee/login'
import { Route as NomineeSecurityRouteImport } from './routes/nominee/security'
import { Route as NomineeTimelineRouteImport } from './routes/nominee/timeline'
import { Route as NomineeVaultRouteImport } from './routes/nominee/vault'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructionsRoute = InstructionsRouteImport.update({
  id: '/instructions',
  path: '/instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NomineesRoute = NomineesRouteImport.update({
  id: '/nominees',
  path: '/nominees',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const NomineeAccessRoute = NomineeAccessRouteImport.update({
  id: '/nominee/access',
  path: '/nominee/access',
  getParentRoute: () => rootRouteImport,
} as any)
const NomineeChecklistRoute = NomineeChecklistRouteImport.update({
  id: '/nominee/checklist',
  path: '/nominee/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const NomineeDashboardRoute = NomineeDashboardRouteImport.update({
  id: '/nominee/dashboard',
  path: '/nominee/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NomineeFinancialRoute = NomineeFinancialRouteImport.update({
  id: '/nominee/financial',
  path: '/nominee/financial',
  getParentRoute: () => rootRouteImport,
} as any)
const NomineeInstructionsRoute = NomineeInstructionsRouteImport.update({
  id: '/nominee/instructions',
  path: '/nominee/instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const NomineeLoginRoute = NomineeLoginRouteImport.update({
  id: '/nominee/login',
  path: '/nominee/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NomineeSecurityRoute = NomineeSecurityRouteImport.update({
  id: '/nominee/security',
  path: '/nominee/security',
  getParentRoute: () => rootRouteImport,
} as any)
const NomineeTimelineRoute = NomineeTimelineRouteImport.update({
  id: '/nominee/timeline',
  path: '/nominee/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const NomineeVaultRoute = NomineeVaultRouteImport.update({
  id: '/nominee/vault',
  path: '/nominee/vault',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/dashboard': typeof DashboardRoute
  '/instructions': typeof InstructionsRoute
  '/login': typeof LoginRoute
  '/nominees': typeof NomineesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/vault': typeof VaultRoute
  '/nominee/access': typeof NomineeAccessRoute
  '/nominee/checklist': typeof NomineeChecklistRoute
  '/nominee/dashboard': typeof NomineeDashboardRoute
  '/nominee/financial': typeof NomineeFinancialRoute
  '/nominee/instructions': typeof NomineeInstructionsRoute
  '/nominee/login': typeof NomineeLoginRoute
  '/nominee/security': typeof NomineeSecurityRoute
  '/nominee/timeline': typeof NomineeTimelineRoute
  '/nominee/vault': typeof NomineeVaultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/dashboard': typeof DashboardRoute
  '/instructions': typeof InstructionsRoute
  '/login': typeof LoginRoute
  '/nominees': typeof NomineesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/vault': typeof VaultRoute
  '/nominee/access': typeof NomineeAccessRoute
  '/nominee/checklist': typeof NomineeChecklistRoute
  '/nominee/dashboard': typeof NomineeDashboardRoute
  '/nominee/financial': typeof NomineeFinancialRoute
  '/nominee/instructions': typeof NomineeInstructionsRoute
  '/nominee/login': typeof NomineeLoginRoute
  '/nominee/security': typeof NomineeSecurityRoute
  '/nominee/timeline': typeof NomineeTimelineRoute
  '/nominee/vault': typeof NomineeVaultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/dashboard': typeof DashboardRoute
  '/instructions': typeof InstructionsRoute
  '/login': typeof LoginRoute
  '/nominees': typeof NomineesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/vault': typeof VaultRoute
  '/nominee/access': typeof NomineeAccessRoute
  '/nominee/checklist': typeof NomineeChecklistRoute
  '/nominee/dashboard': typeof NomineeDashboardRoute
  '/nominee/financial': typeof NomineeFinancialRoute
  '/nominee/instructions': typeof NomineeInstructionsRoute
  '/nominee/login': typeof NomineeLoginRoute
  '/nominee/security': typeof NomineeSecurityRoute
  '/nominee/timeline': typeof NomineeTimelineRoute
  '/nominee/vault': typeof NomineeVaultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/dashboard'
    | '/instructions'
    | '/login'
    | '/nominees'
    | '/settings'
    | '/signup'
    | '/vault'
    | '/nominee/access'
    | '/nominee/checklist'
    | '/nominee/dashboard'
    | '/nominee/financial'
    | '/nominee/instructions'
    | '/nominee/login'
    | '/nominee/security'
    | '/nominee/timeline'
    | '/nominee/vault'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/dashboard'
    | '/instructions'
    | '/login'
    | '/nominees'
    | '/settings'
    | '/signup'
    | '/vault'
    | '/nominee/access'
    | '/nominee/checklist'
    | '/nominee/dashboard'
    | '/nominee/financial'
    | '/nominee/instructions'
    | '/nominee/login'
    | '/nominee/security'
    | '/nominee/timeline'
    | '/nominee/vault'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/dashboard'
    | '/instructions'
    | '/login'
    | '/nominees'
    | '/settings'
    | '/signup'
    | '/vault'
    | '/nominee/access'
    | '/nominee/checklist'
    | '/nominee/dashboard'
    | '/nominee/financial'
    | '/nominee/instructions'
    | '/nominee/login'
    | '/nominee/security'
    | '/nominee/timeline'
    | '/nominee/vault'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  DashboardRoute: typeof DashboardRoute
  InstructionsRoute: typeof InstructionsRoute
  LoginRoute: typeof LoginRoute
  NomineesRoute: typeof NomineesRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  VaultRoute: typeof VaultRoute
  NomineeAccessRoute: typeof NomineeAccessRoute
  NomineeChecklistRoute: typeof NomineeChecklistRoute
  NomineeDashboardRoute: typeof NomineeDashboardRoute
  NomineeFinancialRoute: typeof NomineeFinancialRoute
  NomineeInstructionsRoute: typeof NomineeInstructionsRoute
  NomineeLoginRoute: typeof NomineeLoginRoute
  NomineeSecurityRoute: typeof NomineeSecurityRoute
  NomineeTimelineRoute: typeof NomineeTimelineRoute
  NomineeVaultRoute: typeof NomineeVaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructions': {
      id: '/instructions'
      path: '/instructions'
      fullPath: '/instructions'
      preLoaderRoute: typeof InstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nominees': {
      id: '/nominees'
      path: '/nominees'
      fullPath: '/nominees'
      preLoaderRoute: typeof NomineesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nominee/access': {
      id: '/nominee/access'
      path: '/nominee/access'
      fullPath: '/nominee/access'
      preLoaderRoute: typeof NomineeAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nominee/checklist': {
      id: '/nominee/checklist'
      path: '/nominee/checklist'
      fullPath: '/nominee/checklist'
      preLoaderRoute: typeof NomineeChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nominee/dashboard': {
      id: '/nominee/dashboard'
      path: '/nominee/dashboard'
      fullPath: '/nominee/dashboard'
      preLoaderRoute: typeof NomineeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nominee/financial': {
      id: '/nominee/financial'
      path: '/nominee/financial'
      fullPath: '/nominee/financial'
      preLoaderRoute: typeof NomineeFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nominee/instructions': {
      id: '/nominee/instructions'
      path: '/nominee/instructions'
      fullPath: '/nominee/instructions'
      preLoaderRoute: typeof NomineeInstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nominee/login': {
      id: '/nominee/login'
      path: '/nominee/login'
      fullPath: '/nominee/login'
      preLoaderRoute: typeof NomineeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nominee/security': {
      id: '/nominee/security'
      path: '/nominee/security'
      fullPath: '/nominee/security'
      preLoaderRoute: typeof NomineeSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nominee/timeline': {
      id: '/nominee/timeline'
      path: '/nominee/timeline'
      fullPath: '/nominee/timeline'
      preLoaderRoute: typeof NomineeTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nominee/vault': {
      id: '/nominee/vault'
      path: '/nominee/vault'
      fullPath: '/nominee/vault'
      preLoaderRoute: typeof NomineeVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  DashboardRoute: DashboardRoute,
  InstructionsRoute: InstructionsRoute,
  LoginRoute: LoginRoute,
  NomineesRoute: NomineesRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  VaultRoute: VaultRoute,
  NomineeAccessRoute: NomineeAccessRoute,
  NomineeChecklistRoute: NomineeChecklistRoute,
  NomineeDashboardRoute: NomineeDashboardRoute,
  NomineeFinancialRoute: NomineeFinancialRoute,
  NomineeInstructionsRoute: NomineeInstructionsRoute,
  NomineeLoginRoute: NomineeLoginRoute,
  NomineeSecurityRoute: NomineeSecurityRoute,
  NomineeTimelineRoute: NomineeTimelineRoute,
  NomineeVaultRoute: NomineeVaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
